import React from 'react'
import { Mail, Phone, Upload } from 'lucide-react'
import { InputField, RadioGroup, TextAreaField, FileUploadField } from '../components/FormComponents'

export const STEPS_V1 = [{label:'Identificação'},{label:'Vendas'},{label:'Custos'},{label:'Caixa e Dívidas'},{label:'Visão e Docs'}]

export const FormStepV1 = ({step,formData:fd,setFormData,fieldErrors:fe}) => {
  const set = (k,v) => setFormData({...fd,[k]:v})
  if(step===0) return(<div className="space-y-5"><div className="grid grid-cols-1 md:grid-cols-2 gap-5"><InputField label="Razão Social" value={fd.v1_razao} onChange={v=>set('v1_razao',v)} error={fe.v1_razao} fieldId="v1_razao"/><InputField label="CNPJ" value={fd.v1_cnpj} onChange={v=>set('v1_cnpj',v)} error={fe.v1_cnpj} maskType="cnpj" fieldId="v1_cnpj"/><div className="md:col-span-2"><InputField label="Nome do Responsável" value={fd.v1_responsavel} onChange={v=>set('v1_responsavel',v)} error={fe.v1_responsavel} fieldId="v1_responsavel"/></div><InputField label="Email" value={fd.v1_email} onChange={v=>set('v1_email',v)} error={fe.v1_email} icon={Mail} fieldId="v1_email"/><InputField label="WhatsApp" value={fd.v1_phone} onChange={v=>set('v1_phone',v)} error={fe.v1_phone} icon={Phone} maskType="phone" fieldId="v1_phone"/><div className="md:col-span-2"><InputField label="Segmento de Atuação" placeholder="Ex: Comércio de Roupas..." value={fd.v1_segmento} onChange={v=>set('v1_segmento',v)} error={fe.v1_segmento} fieldId="v1_segmento"/></div><InputField label="Tempo de Operação" placeholder="Ex: 5 anos" value={fd.v1_tempoOperacao} onChange={v=>set('v1_tempoOperacao',v)} error={fe.v1_tempoOperacao} fieldId="v1_tempoOperacao"/><InputField label="Número de Funcionários" value={fd.v1_numFuncionarios} onChange={v=>set('v1_numFuncionarios',v)} error={fe.v1_numFuncionarios} fieldId="v1_numFuncionarios"/><div className="md:col-span-2"><RadioGroup label="Como controla as finanças?" value={fd.v1_controleFinanceiro} options={["Planilha","Sistema / ERP","Contabilidade","Não possui controle"]} onChange={v=>set('v1_controleFinanceiro',v)} error={fe.v1_controleFinanceiro} fieldId="v1_controleFinanceiro"/></div></div></div>)
  if(step===1) return(<div className="space-y-5"><div className="grid grid-cols-1 md:grid-cols-2 gap-5"><InputField label="Faturamento Médio (6 meses)" value={fd.v1_fatMedio} onChange={v=>set('v1_fatMedio',v)} maskType="currency" error={fe.v1_fatMedio} fieldId="v1_fatMedio"/><InputField label="Faturamento Total (12 meses)" value={fd.v1_fat12} onChange={v=>set('v1_fat12',v)} maskType="currency" error={fe.v1_fat12} fieldId="v1_fat12"/><div className="md:col-span-2"><InputField label="Receita: Produtos, Serviços ou Ambos?" subLabel="Se ambos, qual proporção?" placeholder="Ex: 60% produto / 40% serviço" value={fd.v1_mixFaturamento} onChange={v=>set('v1_mixFaturamento',v)} error={fe.v1_mixFaturamento} fieldId="v1_mixFaturamento"/></div><div className="md:col-span-2"><InputField label="Número médio de vendas por mês" value={fd.v1_numVendas} onChange={v=>set('v1_numVendas',v)} error={fe.v1_numVendas} fieldId="v1_numVendas"/></div><div className="md:col-span-2"><RadioGroup label="A empresa gera lucro?" value={fd.v1_lucra} options={["Sim","Não","Não sei"]} onChange={v=>set('v1_lucra',v)} error={fe.v1_lucra} fieldId="v1_lucra"/></div><div className="md:col-span-2"><InputField label="Lucro médio mensal" optional={true} value={fd.v1_lucroMensal} onChange={v=>set('v1_lucroMensal',v)} maskType="currency"/></div><div className="md:col-span-2"><TextAreaField label="Meios de Recebimento" subLabel="Ex: 50% Pix, 30% Cartão, 20% Boleto" value={fd.v1_meios} onChange={v=>set('v1_meios',v)} error={fe.v1_meios} fieldId="v1_meios"/></div><InputField label="Impostos sobre Vendas" optional={true} value={fd.v1_impostos} onChange={v=>set('v1_impostos',v)} placeholder="R$ ou %"/><InputField label="Taxa de Inadimplência" value={fd.v1_inadimplencia} onChange={v=>set('v1_inadimplencia',v)} error={fe.v1_inadimplencia} fieldId="v1_inadimplencia"/></div></div>)
  if(step===2) return(<div className="space-y-5"><p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest pb-2 border-b border-slate-100">Custos Diretos</p><InputField label="Custo com Mercadorias ou Serviços" subLabel="Valor médio mensal." value={fd.v1_custosDiretos} onChange={v=>set('v1_custosDiretos',v)} maskType="currency" error={fe.v1_custosDiretos} fieldId="v1_custosDiretos"/><InputField label="Taxas de Recebimento" subLabel="Maquininhas, gateways, boleto." value={fd.v1_taxaRecebimento} onChange={v=>set('v1_taxaRecebimento',v)} maskType="currency" error={fe.v1_taxaRecebimento} fieldId="v1_taxaRecebimento"/><InputField label="Comissões" optional={true} value={fd.v1_comissoes} onChange={v=>set('v1_comissoes',v)} maskType="currency"/><p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest pb-2 border-b border-slate-100 pt-4">Despesas Fixas</p><div className="grid grid-cols-1 md:grid-cols-2 gap-5"><InputField label="Folha de Pagamento" value={fd.v1_folha} onChange={v=>set('v1_folha',v)} maskType="currency" error={fe.v1_folha} fieldId="v1_folha"/><InputField label="Pró-labore dos Sócios" value={fd.v1_prolabore} onChange={v=>set('v1_prolabore',v)} maskType="currency" error={fe.v1_prolabore} fieldId="v1_prolabore"/><InputField label="Marketing e Anúncios" value={fd.v1_mkt} onChange={v=>set('v1_mkt',v)} maskType="currency" error={fe.v1_mkt} fieldId="v1_mkt"/><InputField label="Estrutura e Consumo" subLabel="Aluguel, Luz, Internet, Software" value={fd.v1_estrutura} onChange={v=>set('v1_estrutura',v)} maskType="currency" error={fe.v1_estrutura} fieldId="v1_estrutura"/><div className="md:col-span-2"><InputField label="Outras Despesas Fixas" value={fd.v1_outrasFixas} onChange={v=>set('v1_outrasFixas',v)} maskType="currency"/></div></div></div>)
  if(step===3) return(<div className="space-y-5"><TextAreaField label="A empresa possui dívidas?" subLabel="Se não, escreva 'Não'." value={fd.v1_descricaoDividas} onChange={v=>set('v1_descricaoDividas',v)} error={fe.v1_descricaoDividas} fieldId="v1_descricaoDividas"/><div className="grid grid-cols-1 md:grid-cols-2 gap-5"><InputField label="Valor total das dívidas" optional={true} value={fd.v1_valorTotalDividas} onChange={v=>set('v1_valorTotalDividas',v)} maskType="currency"/><InputField label="Parcelas Mensais" optional={true} value={fd.v1_pesoDivida} onChange={v=>set('v1_pesoDivida',v)} maskType="currency"/><InputField label="Prazo Médio Recebimento (dias)" optional={true} value={fd.v1_prazoRec} onChange={v=>set('v1_prazoRec',v)}/><InputField label="Prazo Médio Pagamento (dias)" optional={true} value={fd.v1_prazoPag} onChange={v=>set('v1_prazoPag',v)}/></div><p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest pb-2 border-b border-slate-100 pt-4">Posição de Caixa</p><div className="grid grid-cols-1 md:grid-cols-2 gap-5"><InputField label="Saldo atual em banco/caixa" value={fd.v1_saldo} onChange={v=>set('v1_saldo',v)} maskType="currency" error={fe.v1_saldo} fieldId="v1_saldo"/><InputField label="Reserva financeira" subLabel="Caso não possua, informar 0" value={fd.v1_reserva} onChange={v=>set('v1_reserva',v)} maskType="currency" error={fe.v1_reserva} fieldId="v1_reserva"/></div><InputField label="Valor em Estoque" optional={true} value={fd.v1_estoque} onChange={v=>set('v1_estoque',v)}/><TextAreaField label="Pretende contratar crédito em breve?" value={fd.v1_detalhesCredito} onChange={v=>set('v1_detalhesCredito',v)} error={fe.v1_detalhesCredito} fieldId="v1_detalhesCredito"/></div>)
  if(step===4) return(<div className="space-y-5"><TextAreaField label="Maior desafio financeiro hoje?" value={fd.v1_desafio} onChange={v=>set('v1_desafio',v)} error={fe.v1_desafio} fieldId="v1_desafio"/><TextAreaField label="Objetivo para os próximos 12 meses?" value={fd.v1_objetivo} onChange={v=>set('v1_objetivo',v)} error={fe.v1_objetivo} fieldId="v1_objetivo"/><div className="bg-slate-50/50 p-6 rounded-2xl border border-dashed border-slate-200 space-y-4"><div className="flex items-center gap-2"><Upload size={13} className="text-slate-400"/><p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Documentos</p><span className="ml-auto text-[9px] bg-slate-100 text-slate-400 px-2 py-0.5 rounded-full font-bold">Opcional</span></div><TextAreaField label="Links de Planilhas" optional={true} placeholder="https://docs.google.com/..." value={fd.v1_linksAnexos} onChange={v=>set('v1_linksAnexos',v)}/><FileUploadField onFilesSelected={n=>set('v1_nomesArquivos',n)}/></div></div>)
  return null
}

export const STEPS_G = [{label:'Identificação'},{label:'Negócio e Vendas'},{label:'Gastos'},{label:'Dívidas e Caixa'},{label:'Futuro e Docs'}]

export const FormStepG = ({step,formData:fd,setFormData,fieldErrors:fe}) => {
  const set = (k,v) => setFormData({...fd,[k]:v})
  if(step===0) return(<div className="space-y-5"><div className="grid grid-cols-1 md:grid-cols-2 gap-5"><InputField label="Razão Social" value={fd.g_razao} onChange={v=>set('g_razao',v)} error={fe.g_razao} fieldId="g_razao"/><InputField label="CNPJ" value={fd.g_cnpj} onChange={v=>set('g_cnpj',v)} error={fe.g_cnpj} maskType="cnpj" fieldId="g_cnpj"/><div className="md:col-span-2"><InputField label="Nome do Responsável" value={fd.g_responsavel} onChange={v=>set('g_responsavel',v)} error={fe.g_responsavel} fieldId="g_responsavel"/></div><InputField label="Email" value={fd.g_email} onChange={v=>set('g_email',v)} error={fe.g_email} icon={Mail} fieldId="g_email"/><InputField label="WhatsApp" value={fd.g_phone} onChange={v=>set('g_phone',v)} error={fe.g_phone} icon={Phone} maskType="phone" fieldId="g_phone"/></div></div>)
  if(step===1) return(<div className="space-y-5"><TextAreaField label="A empresa vende Produtos, Serviços ou os dois?" value={fd.g_oqueVende} onChange={v=>set('g_oqueVende',v)} error={fe.g_oqueVende} fieldId="g_oqueVende"/><InputField label="Há quanto tempo existe?" value={fd.g_tempoExistencia} onChange={v=>set('g_tempoExistencia',v)} error={fe.g_tempoExistencia} fieldId="g_tempoExistencia"/><InputField label="Quantas pessoas trabalham?" value={fd.g_pessoas} onChange={v=>set('g_pessoas',v)} error={fe.g_pessoas} fieldId="g_pessoas"/><InputField label="Faturamento mensal" value={fd.g_faturamento} onChange={v=>set('g_faturamento',v)} maskType="currency" error={fe.g_faturamento} fieldId="g_faturamento"/><InputField label="De onde vem a maior parte do dinheiro?" value={fd.g_mixFaturamento} onChange={v=>set('g_mixFaturamento',v)} error={fe.g_mixFaturamento} fieldId="g_mixFaturamento"/><InputField label="Principais meios de recebimento?" value={fd.g_meioVenda} onChange={v=>set('g_meioVenda',v)} error={fe.g_meioVenda} fieldId="g_meioVenda"/><InputField label="Com que frequência realiza vendas?" value={fd.g_frequencia} onChange={v=>set('g_frequencia',v)} error={fe.g_frequencia} fieldId="g_frequencia"/><TextAreaField label="Como avalia a precificação?" value={fd.g_sobrePreco} onChange={v=>set('g_sobrePreco',v)} error={fe.g_sobrePreco} fieldId="g_sobrePreco"/><InputField label="Produto/serviço mais lucrativo?" value={fd.g_produtoLucrativo} onChange={v=>set('g_produtoLucrativo',v)} error={fe.g_produtoLucrativo} fieldId="g_produtoLucrativo"/></div>)
  if(step===2) return(<div className="space-y-5"><div className="grid grid-cols-1 md:grid-cols-2 gap-5"><InputField label="Aluguel mensal" value={fd.g_aluguel} onChange={v=>set('g_aluguel',v)} maskType="currency" error={fe.g_aluguel} fieldId="g_aluguel"/><InputField label="Gasto com funcionários" value={fd.g_gastoFunc} onChange={v=>set('g_gastoFunc',v)} maskType="currency" error={fe.g_gastoFunc} fieldId="g_gastoFunc"/><InputField label="Seu salário (pró-labore)" value={fd.g_prolabore} onChange={v=>set('g_prolabore',v)} maskType="currency" error={fe.g_prolabore} fieldId="g_prolabore"/><InputField label="Gastos com mercadorias/serviço" value={fd.g_custosDiretos} onChange={v=>set('g_custosDiretos',v)} maskType="currency" error={fe.g_custosDiretos} fieldId="g_custosDiretos"/><InputField label="Taxas de maquininha" value={fd.g_taxaMaquininha} onChange={v=>set('g_taxaMaquininha',v)} maskType="currency" error={fe.g_taxaMaquininha} fieldId="g_taxaMaquininha"/><InputField label="Outros gastos fixos" subLabel="Água, luz, internet, contador" value={fd.g_outrosFixos} onChange={v=>set('g_outrosFixos',v)} maskType="currency" error={fe.g_outrosFixos} fieldId="g_outrosFixos"/></div><TextAreaField label="Maior 'ralo' de dinheiro hoje?" value={fd.g_raloDinheiro} onChange={v=>set('g_raloDinheiro',v)} error={fe.g_raloDinheiro} fieldId="g_raloDinheiro"/></div>)
  if(step===3) return(<div className="space-y-5"><TextAreaField label="Possui empréstimos ou dívidas?" subLabel="Se não, escreva 'Não'." value={fd.g_descricaoDividas} onChange={v=>set('g_descricaoDividas',v)} error={fe.g_descricaoDividas} fieldId="g_descricaoDividas"/><div className="grid grid-cols-1 md:grid-cols-2 gap-5"><InputField label="Valor total das dívidas" optional={true} value={fd.g_valorTotalDivida} onChange={v=>set('g_valorTotalDivida',v)} maskType="currency"/><InputField label="Como está o pagamento das contas?" value={fd.g_contasEmDia} onChange={v=>set('g_contasEmDia',v)} error={fe.g_contasEmDia} fieldId="g_contasEmDia"/><InputField label="Mistura contas da empresa com pessoais?" value={fd.g_misturaContas} onChange={v=>set('g_misturaContas',v)} error={fe.g_misturaContas} fieldId="g_misturaContas"/><InputField label="Se parar de vender, quanto tempo sobrevive?" value={fd.g_folegoCaixa} onChange={v=>set('g_folegoCaixa',v)} error={fe.g_folegoCaixa} fieldId="g_folegoCaixa"/></div><TextAreaField label="Pensa em pegar empréstimo?" optional={true} value={fd.g_querEmprestimo} onChange={v=>set('g_querEmprestimo',v)}/><InputField label="Em quantos meses pagaria?" optional={true} value={fd.g_prazoPagamento} onChange={v=>set('g_prazoPagamento',v)}/></div>)
  if(step===4) return(<div className="space-y-5"><TextAreaField label="Maior desafio financeiro?" value={fd.g_desafio} onChange={v=>set('g_desafio',v)} error={fe.g_desafio} fieldId="g_desafio"/><TextAreaField label="Se nada mudar, o que acontece em 3 meses?" value={fd.g_futuro} onChange={v=>set('g_futuro',v)} error={fe.g_futuro} fieldId="g_futuro"/><div className="bg-slate-50/50 p-6 rounded-2xl border border-dashed border-slate-200 space-y-4"><div className="flex items-center gap-2"><Upload size={13} className="text-slate-400"/><p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Documentos</p><span className="ml-auto text-[9px] bg-slate-100 text-slate-400 px-2 py-0.5 rounded-full font-bold">Opcional</span></div><TextAreaField label="Links de Planilhas" optional={true} placeholder="https://docs.google.com/..." value={fd.g_linksAnexos} onChange={v=>set('g_linksAnexos',v)}/><FileUploadField onFilesSelected={n=>set('g_nomesArquivos',n)}/></div></div>)
  return null
}

export const EMPTY_FORM = {
  v1_razao:'',v1_cnpj:'',v1_responsavel:'',v1_email:'',v1_phone:'',v1_segmento:'',
  v1_tempoOperacao:'',v1_numFuncionarios:'',v1_controleFinanceiro:'',
  v1_fatMedio:'',v1_fat12:'',v1_mixFaturamento:'',v1_numVendas:'',v1_meios:'',v1_impostos:'',v1_inadimplencia:'',
  v1_lucra:'',v1_lucroMensal:'',v1_custosDiretos:'',v1_taxaRecebimento:'',v1_comissoes:'',
  v1_folha:'',v1_prolabore:'',v1_mkt:'',v1_estrutura:'',v1_outrasFixas:'',
  v1_descricaoDividas:'',v1_pesoDivida:'',v1_valorTotalDividas:'',v1_prazoRec:'',v1_prazoPag:'',
  v1_saldo:'',v1_reserva:'',v1_estoque:'',v1_detalhesCredito:'',v1_desafio:'',v1_objetivo:'',
  v1_linksAnexos:'',v1_nomesArquivos:'',
  g_razao:'',g_cnpj:'',g_responsavel:'',g_email:'',g_phone:'',g_oqueVende:'',g_tempoExistencia:'',g_pessoas:'',
  g_faturamento:'',g_mixFaturamento:'',g_meioVenda:'',g_frequencia:'',g_sobrePreco:'',g_produtoLucrativo:'',
  g_aluguel:'',g_gastoFunc:'',g_prolabore:'',g_custosDiretos:'',g_taxaMaquininha:'',g_outrosFixos:'',g_raloDinheiro:'',
  g_descricaoDividas:'',g_valorTotalDivida:'',g_contasEmDia:'',g_misturaContas:'',
  g_folegoCaixa:'',g_estoque:'',g_querEmprestimo:'',g_finalidadeEmprestimo:'',g_prazoPagamento:'',
  g_desafio:'',g_futuro:'',g_linksAnexos:'',g_nomesArquivos:''
}

export const SCENARIOS = [
  {id:'aumentar_ticket',group:'Receita',     emoji:'📈',label:'Aumentar Preço',        desc:'Cobrar % a mais por venda ou serviço',            tipo:'pct',   inputLabel:'Aumento no preço (%)'},
  {id:'queda_receita',  group:'Receita',     emoji:'📉',label:'Queda na Receita',       desc:'Simule sazonalidade ou perda de clientes',        tipo:'pct',   inputLabel:'Queda percentual (%)'},
  {id:'perda_cliente',  group:'Receita',     emoji:'⚠️', label:'Perder Cliente Fixo',   desc:'Receita mensal que deixaria de entrar',           tipo:'valor', inputLabel:'Receita perdida/mês'},
  {id:'novo_contrato',  group:'Receita',     emoji:'🤝', label:'Novo Contrato',         desc:'Receita extra entrando todo mês',                 tipo:'valor', inputLabel:'Valor do contrato/mês'},
  {id:'contratar_func', group:'Custo',       emoji:'👤',label:'Contratar Funcionário',  desc:'Salário base (+30% encargos calculado)',          tipo:'valor', inputLabel:'Salário base mensal'},
  {id:'nova_despesa',   group:'Custo',       emoji:'🏢',label:'Nova Despesa Fixa',      desc:'Aluguel, assinatura, licença ou serviço',         tipo:'valor', inputLabel:'Valor mensal'},
  {id:'reduzir_custo',  group:'Custo',       emoji:'✂️', label:'Cortar Custo Fixo',     desc:'Renegociação ou eliminação de despesa',           tipo:'valor', inputLabel:'Economia mensal'},
  {id:'investimento',   group:'Investimento',emoji:'⚙️', label:'Investimento à Vista',  desc:'Sai do caixa imediatamente (equip. ou reforma)', tipo:'valor', inputLabel:'Valor do investimento'},
  {id:'emprestimo',     group:'Dívida',      emoji:'🏦',label:'Captar Empréstimo',      desc:'Entra no caixa; parcela fixada em 12x',           tipo:'valor', inputLabel:'Valor captado'},
  {id:'pagar_divida',   group:'Dívida',      emoji:'🎯',label:'Quitar Parcela Mensal',  desc:'Elimina custo fixo mensal, consome caixa hoje',   tipo:'valor', inputLabel:'Parcela quitada/mês'},
]
